// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");

require("./AnalogClock.css");

function AnalogClock(Props) {
  var date = Props.date;
  var secondstyle = ReactDOMRe.Style.unsafeAddProp({ }, "--current-seconds", new Date(date).getSeconds().toString());
  var minutestyle = ReactDOMRe.Style.unsafeAddProp({ }, "--current-minutes", new Date(date).getMinutes().toString());
  var hourstyle = ReactDOMRe.Style.unsafeAddProp({ }, "--current-hours", new Date(date).getHours().toString());
  return React.createElement("svg", {
              className: "analogClock",
              viewBox: "0 0 40 40"
            }, React.createElement("circle", {
                  className: "analogClockFace",
                  cx: "20",
                  cy: "20",
                  r: "19"
                }), React.createElement("g", {
                  className: "marks"
                }, React.createElement("line", {
                      x1: "15",
                      x2: "16",
                      y1: "0",
                      y2: "0"
                    }), React.createElement("line", {
                      x1: "15",
                      x2: "16",
                      y1: "0",
                      y2: "0"
                    }), React.createElement("line", {
                      x1: "15",
                      x2: "16",
                      y1: "0",
                      y2: "0"
                    }), React.createElement("line", {
                      x1: "15",
                      x2: "16",
                      y1: "0",
                      y2: "0"
                    }), React.createElement("line", {
                      x1: "15",
                      x2: "16",
                      y1: "0",
                      y2: "0"
                    }), React.createElement("line", {
                      x1: "15",
                      x2: "16",
                      y1: "0",
                      y2: "0"
                    }), React.createElement("line", {
                      x1: "15",
                      x2: "16",
                      y1: "0",
                      y2: "0"
                    }), React.createElement("line", {
                      x1: "15",
                      x2: "16",
                      y1: "0",
                      y2: "0"
                    }), React.createElement("line", {
                      x1: "15",
                      x2: "16",
                      y1: "0",
                      y2: "0"
                    }), React.createElement("line", {
                      x1: "15",
                      x2: "16",
                      y1: "0",
                      y2: "0"
                    }), React.createElement("line", {
                      x1: "15",
                      x2: "16",
                      y1: "0",
                      y2: "0"
                    }), React.createElement("line", {
                      x1: "15",
                      x2: "16",
                      y1: "0",
                      y2: "0"
                    })), React.createElement("line", {
                  className: "hour",
                  style: hourstyle,
                  x1: "0",
                  x2: "9",
                  y1: "0",
                  y2: "0"
                }), React.createElement("line", {
                  className: "minute",
                  style: minutestyle,
                  x1: "0",
                  x2: "13",
                  y1: "0",
                  y2: "0"
                }), React.createElement("line", {
                  className: "seconds",
                  style: secondstyle,
                  x1: "0",
                  x2: "16",
                  y1: "0",
                  y2: "0"
                }), React.createElement("circle", {
                  className: "pin",
                  cx: "20",
                  cy: "20",
                  r: "0.7"
                }));
}

var make = AnalogClock;

exports.make = make;
/*  Not a pure module */
