// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var AnyHooksClock$ReasonAnyhooksDemo = require("./AnyHooksClock.bs.js");
var ReactHooksClock$ReasonAnyhooksDemo = require("./ReactHooksClock.bs.js");

require("./index.css");

function Index$Clocks(Props) {
  return React.createElement("div", {
              className: "grid-container"
            }, React.createElement(ReactHooksClock$ReasonAnyhooksDemo.make, { }), React.createElement(AnyHooksClock$ReasonAnyhooksDemo.make, { }));
}

var Clocks = {
  make: Index$Clocks
};

ReactDOMRe.renderToElementWithId(React.createElement(Index$Clocks, { }), "use-clock");

exports.Clocks = Clocks;
/*  Not a pure module */
