// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Constant$ReasonAnyhooks = require("reason-anyhooks/src/Constant.bs.js");
var Hooks$ReasonAnyhooksDemo = require("./Hooks.bs.js");
var AnalogClock$ReasonAnyhooksDemo = require("./AnalogClock.bs.js");

function ReactHooksClock(Props) {
  var date = Hooks$ReasonAnyhooksDemo.useClock(/* () */0);
  var constant = Constant$ReasonAnyhooks.useConstant((function (param) {
          return 23;
        }));
  var anotherConstant = constant + 1 | 0;
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Using React Hooks"), React.createElement("h1", undefined, "Mixing Hooks!, constant from AnyHooks: " + String(anotherConstant)), React.createElement(AnalogClock$ReasonAnyhooksDemo.make, {
                  date: date
                }));
}

var make = ReactHooksClock;

exports.make = make;
/* react Not a pure module */
